version: "3"

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PW}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    expose:
      # Opens port 3306 on the container
      - ${DB_DOCKER_PORT}
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

    env_file:
      - ./next-app/.env


  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - ./next-app/.env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
  # Add more containers below (nginx, postgres, etc.)




    # Define a network, which allows containers to communicate
    # with each other, by using their container name as a hostname
networks:
  my_network:
    external: true

volumes:
  my-db:
