import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar"
import colors from "colors"
import { SettingsProvider } from '@/contexts/SettingsContext';
import { AuthProvider } from '@/contexts/AuthContext';
// import { NavigationProvider } from '@/components/loading/NavigationProvider';
// import ProgressProvider from '@/components/loading/ProgressProvider';

colors.enable()

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Fortoon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SettingsProvider>
        {/* <NavigationProvider>
          <ProgressProvider> */}
            <Navbar />
            {children}
          {/* </ProgressProvider>
        </NavigationProvider> */}
          </SettingsProvider>
        </AuthProvider>
           
      </body>
    </html>
  );
}
